[versions]
mod-version = "0.1.0"

# Fabric (https://fabricmc.net/develop)
minecraftVersion="1.21.4"
yarn_mappings="1.21.4+build.8"
loader_version="0.19.2"
loom_version="1.16.1"

# Fabric API
fabric_api_version="0.119.4+1.21.4"

# Meteor (https://github.com/MeteorDevelopment/meteor-client/)
meteor = "1.21.4-SNAPSHOT"

# Mods

[libraries]
# Fabric base
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraftVersion" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader_version" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api_version" }
# Meteor client
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

# Mods

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom_version" }


